### PR TITLE
Bug/windows version not calculated correctly

### LINKED ISSUE #4: Windows version not reported correctly in automatic mode
Tested with a laptop running Windows 10 Pro, 64bit. OS reported as Windows 8.

In Windows 8.1 and 10, [getVersion has been deprecated](https://msdn.microsoft.com/en-us/library/windows/desktop/dn481241(v=vs.85).aspx)

### PR DESCRIPTION
**Pull request by mjjs**
This fixes #4 by checking Windows registry for the version instead of using the deprecated getVersion().

### CODE REVIEW

File: nvdfetch.go [hunk 1]
```diff
@@ -130,24 +131,32 @@ func getDownloadUrl(psId, pfId, osId int) string {
...
-		return 7
-	case "6.2":
-		return 8
-	case "10.0":
-		return 10
-	default:
-		// Default to Windows 10 because it's the newest
+	defer k.Close()
+
+	_, _, err = k.GetStringValue("CurrentMajorVersionNumber")
```
Comment (mjjs) [inline nvdfetch.go]: Needs to check for integer value instead of string
